export const FIND_USER_REQUEST = "FIND_USER_REQUEST";
export const FIND_USER_REQUEST_SUCCESS = "FIND_USER_REQUEST_SUCCESS";
export const FIND_USER_REQUEST_FAIL = "FIND_USER_REQUEST_FAIL";
export const CHANGE_INPUT_VALUE_FIND_USER = "CHANGE_INPUT_VALUE_FIND_USER";
export const CHANGE_INPUT_VALUE_USER_FORM= "CHANGE_INPUT_VALUE_USER_FORM";
export const CHANGE_INPUT_VALUE_USER_USER_FORM = "CHANGE_INPUT_VALUE_USER_USER_FORM"
export const CHANGE_DATA_IN_CURRENT_USER = "CHANGE_DATA_IN_CURRENT_USER"

export const FIND_ORDERS_ARRAY = "FIND_ORDERS_ARRAY";
export const CHANGE_INPUT_VALUE_FIND_ORDER = "CHANGE_INPUT_VALUE_FIND_ORDER";
export const CHANGE_INPUT_VALUE_ORDER_FORM= "CHANGE_INPUT_VALUE_ORDER_FORM";

export const GET_USERS_REQUEST = "GET_USERS_REQUEST";
export const GET_USERS_REQUEST_SUCCESS = "GET_USERS_REQUEST_SUCCESS";
export const GET_USERS_REQUEST_FAIL = "GET_USERS_REQUEST_FAIL";

export const GET_DOCTORS_REQUEST = "GET_DOCTORS_REQUEST";
export const GET_DOCTORS_REQUEST_SUCCESS = "GET_DOCTORS_REQUEST_SUCCESS";
export const GET_DOCTORS_REQUEST_FAIL = "GET_DOCTORS_REQUEST_FAIL";

export const GET_SERVICES_REQUEST = "GET_SERVICES_REQUEST";
export const GET_SERVICES_REQUEST_SUCCESS = "GET_SERVICES_REQUEST_SUCCESS";
export const GET_SERVICES_REQUEST_FAIL = "GET_SERVICES_REQUEST_FAIL";

export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_REQUEST_SUCCESS = "GET_CATEGORIES_REQUEST_SUCCESS";
export const GET_CATEGORIES_REQUEST_FAIL = "GET_CATEGORIES_REQUEST_FAIL";

export const CHANGE_APPOINTMENT_SHEDULE= "CHANGE_APPOINTMENT_SHEDULE";
export const CHANGE_APPOINTMENT_DOCTOR= "CHANGE_APPOINTMENT_DOCTOR";
export const CHANGE_APPOINTMENT_TIME= "CHANGE_APPOINTMENT_TIME";
export const CHANGE_APPOINTMENT_SPEC= "CHANGE_APPOINTMENT_SPEC";
export const CHANGE_APPOINTMENT_COMMENT= "CHANGE_APPOINTMENT_COMMENT";
export const CLEAR_APPOINTMENT= "CLEAR_APPOINTMENT";

export const AUTH_REQUEST = "GET_AUTH_REQUEST";
export const AUTH_REQUEST_SUCCESS = "AUTH_REQUEST_SUCCESS";
export const AUTH_REQUEST_FAIL = "AUTH_REQUEST_FAIL";

export const REGISTRATION_REQUEST = "REQISTRATION_REQUEST";
export const REGISTRATION_REQUEST_SUCCESS = "REGISTRATION_REQUEST_SUCCESS";
export const REGISTRATION_REQUEST_FAIL = "REGISTRATION_REQUEST_FAIL";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_REQUEST_SUCCESS = "GET_USER_REQUEST_SUCESS";
export const GET_USER_REQUEST_FAIL = "GET_USER_REQUEST_FAIL";

export const USER_LOGOUT = "USER_LOGOUT"

export const POST_DOCTORS_REQUEST = "POST_DOCTORS_REQUEST";
export const POST_DOCTORS_REQUEST_SUCCESS = "POST_DOCTORS_REQUEST_SUCCESS";
export const POST_DOCTORS_REQUEST_FAIL = "POST_DOCTORS_REQUEST_FAIL";

export const POST_SERVICES_REQUEST = "POST_SERVICES_REQUEST";
export const POST_SERVICES_REQUEST_SUCCESS = "POST_SERVICES_REQUEST_SUCCESS";
export const POST_SERVICES_REQUEST_FAIL = "POST_SERVICES_REQUEST_FAIL";

export const POST_ORDERS_REQUEST = "POST_ORDERS_REQUEST";
export const POST_ORDERS_REQUEST_SUCCESS = "POST_ORDERS_REQUEST_SUCCESS";
export const POST_ORDERS_REQUEST_FAIL = "POST_ORDERS_REQUEST_FAIL";

export const POST_SHEDULE_REQUEST = "POST_SHEDULE_REQUEST";
export const POST_SHEDULE_REQUEST_SUCCESS = "POST_SHEDULE_REQUEST_SUCCESS";
export const POST_SHEDULE_REQUEST_FAIL = "POST_SHEDULE_REQUEST_FAIL";

export const PUT_DOCTORS_REQUEST = "PUT_DOCTORS_REQUEST";
export const PUT_DOCTORS_REQUEST_SUCCESS = "PUT_DOCTORS_REQUEST_SUCCESS";
export const PUT_DOCTORS_REQUEST_FAIL = "PUT_DOCTORS_REQUEST_FAIL";

export const PUT_USER_REQUEST = "PUT_USER_REQUEST";
export const PUT_USER_REQUEST_SUCCESS = "PUT_USER_REQUEST_SUCCESS";
export const PUT_USER_REQUEST_FAIL = "PUT_USER_REQUEST_FAIL";

export const PUT_SERVICES_REQUEST = "PUT_DOCTORS_REQUEST";
export const PUT_SERVICES_REQUEST_SUCCESS = "PUT_DOCTORS_REQUEST_SUCCESS";
export const PUT_SERVICES_REQUEST_FAIL = "PUT_DOCTORS_REQUEST_FAIL";

export const DELETE_DOCTORS_REQUEST = "DELETE_DOCTORS_REQUEST";
export const DELETE_DOCTORS_REQUEST_SUCCESS = "DELETE_DOCTORS_REQUEST_SUCCESS";
export const DELETE_DOCTORS_REQUEST_FAIL = "DELETE_DOCTORS_REQUEST_FAIL";

export const DELETE_SERVICES_REQUEST = "DELETE_DOCTORS_REQUEST";
export const DELETE_SERVICES_REQUEST_SUCCESS = "DELETE_DOCTORS_REQUEST_SUCCESS";
export const DELETE_SERVICES_REQUEST_FAIL = "DELETE_DOCTORS_REQUEST_FAIL";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_REQUEST_SUCCESS = "DELETE_USER_REQUEST_SUCCESS";
export const DELETE_USER_REQUEST_FAIL = "DELETE_USER_REQUEST_FAIL";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_REQUEST_SUCCESS = "DELETE_ORDER_REQUEST_SUCCESS";
export const DELETE_ORDER_REQUEST_FAIL = "DELETE_ORDER_REQUEST_FAIL";

export const CHANGE_SHEDULE_DOCTOR= "CHANGE_SHEDULE_DOCTOR";

export const CHANGE_INPUT_VALUE_DOCTOR_FORM= "CHANGE_INPUT_VALUE_DOCTOR_FORM";
export const CHANGE_INPUT_VALUE_SERVICE_FORM= "CHANGE_INPUT_VALUE_SERVICE_FORM";
export const CHANGE_SELECTED_DOCTOR_ID= "CHANGE_SELECTED_DOCTOR_ID";
export const CHANGE_SELECTED_SERVICE_ID= "CHANGE_SELECTED_SERVICE_ID";
export const CHANGE_SPECIALITY_ARRAY= "CHANGE_SPECIALITY_ARRAY";

export const CREATE_CALENDAR_MONTH_ARRAY= "CREATE_CALENDAR_MONTH_ARRAY";
export const CHANGE_CALENDAR_MONTH= "CHANGE_CALENDAR_MONTH";
export const RESET_CALENDAR_CURRENT= "RESET_CALENDAR_CURRENT";

export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
export const GET_ORDERS_REQUEST_SUCCESS = "GET_ORDERS_REQUEST_SUCCESS";
export const GET_ORDERS_REQUEST_FAIL = "GET_ORDERS_REQUEST_FAIL";
export const USER_ORDERS = "USER_ORDERS"







